#!/bin/sh

python createdb.py
python hellodjango/manage.py syncdb --noinput
python mkadmin.py
mkdir -p /home/dotcloud/data/media /home/dotcloud/volatile/static
python wedding/manage.py collectstatic --noinput